on:
  push:
    branches:
      - '*'

jobs:
  generate_matrix:
    name: Find services
    runs-on: ubuntu-latest
    outputs:
      matrix: "{\"path\": ${{ steps.generate_matrix.outputs.matrix }} }"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate matrix
        id: generate_matrix
        uses: jakubsacha-test/matrix-git-generator@master
        with:
          filters: |
            services/*/**
      - name: debug
        run: |
          echo ${{ steps.generate_matrix.outputs.matrix }}

  build:
    if: needs.generate_matrix.outputs.empty != true
    needs: [generate_matrix]
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    uses: jakubsacha-test/workflows/.github/workflows/ci-cd-autopromote.yaml@main
    with:
      ref: ${{ github.ref }}
      application-name: "${{ matrix.path }}"
      target-cluster: interface
      working-directory: ${{ matrix.path }}
  