on:
  push:
    branches:
      - '*'

jobs:
  generate_matrix:
    name: Find services
    runs-on: ubuntu-latest
    outputs:
      matrix: "{\"path\": ${{ steps.generate_matrix.outputs.matrix }} }"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate matrix
        id: generate_matrix
        uses: jakubsacha/action-matrix-monorepo@master
        with:
          filters: |
            services/*/**
          depth: 3
          alwaysTriggerDirs: |
            ci/**
            .github/workflows/**
          base: main
          
  build:
    if: needs.generate_matrix.outputs.empty != true
    needs: [generate_matrix]
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    uses: jakubsacha-test/workflows/.github/workflows/ci-cd-autopromote.yaml@main
    with:
      ref: ${{ github.ref }}
      application-name: "${{ matrix.path }}" #todo: replace with the "application name" derived from the folder structure. btw. Do we even need it?
      target-cluster: interface
      working-directory: ${{ matrix.path }}
  
